version: "3.7"
services:
  # mqtt5 eclipse-mosquitto
  mqtt5:
    image: eclipse-mosquitto
    container_name: mqtt5
    ports:
      - "1883:1883" #default mqtt port
      - "9001:9001" #default mqtt port for websockets
    volumes:
      - ./mqtt/config:/mosquitto/config:rw
      - ./mqtt/data:/mosquitto/data:rw
      - ./mqtt/log:/mosquitto/log:rw
    restart: unless-stopped
  
  mqtt-client:
    build: ./python-mqtt-ingest
    depends_on:
      - mqtt5
    volumes:
      - ./python-mqtt-ingest/mqtt-ingester.py:/mqtt-ingester.py  # Update path based on file location
  mqtt-test-send:
    build: ./mqtt-test-send
    depends_on:
      - mqtt-client
    volumes:
      - ./pmqtt-test-send/mqtt-sender.py:/mqtt-sender.py  # Update path based on file location

# volumes for mapping data,config and log
volumes:
  config:
  data:
  log:

networks:
  default:
    name: mqtt5-network